spring.application.name=order-service

spring.datasource.url=jdbc:mysql://localhost:3307/orders_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092


# Tell Kafka to use the JsonDeserializer for values
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell the JsonDeserializer which package/classes are "trusted" to be converted
# Use "*" to allow all, or provide your specific package
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Map the incoming JSON specifically to your DTO
spring.kafka.consumer.properties.spring.json.value.default.type=com.pavan.order_service.dto.OrderEventDTO